# The Problem

One of the biggest problems in science is the inadvertent destruction of data and the inaccessibility of data due to poor labeling and description of data. This loss of data means that studies cannot be replicated, combined or re-used in different settings [@Briney2015; @Wilkinson2016]. Data management becomes more important, but also more challenging, in the age of rapid digital data production. The Integrated Rule-Oriented Data System ([iRODS](https://irods.org/)) [@Rajasekar2010; @Rajasekar2015] is an open sourced data management software suite that offers a solution to this demand, which encompasses the whole data life cycle from data generation, storage and recycling. The loosely constructed and highly configurable architecture of iRODS frees the user from strict formatting constrains and single-vendor solutions. Furthermore, the open-sourced and community supported nature of iRODS safeguards data storage and re-usability of data in terms of longevity and independently of future technological innovations.

Nonetheless, the learning curve of how to implement iRODS effectively for day-to-day data management purposes can be steep for the average scientist. Hence there have been multiple incentives to lower this barrier by hiding parts of the behind-the-scenes business logic which requires considerable knowledge of command line tools. A notable example is the UU developed YODA front-end, which simplifies the scientist's tasks to meet their datamanagement goals. But, it still requires some effort to integrate this data representation with workflows for the analyses of data. Highly popular among academics are higher level programming languages, such as R, that can help construct such data analyses workflows. Currently, there is no straightforward solution to integrate iRODS data storage with R workflows. The development of the R package *rirods* [@rirods], build on top of the iRODS C++ API, is currently stale and suffers from strict system requirements constrains, which makes it unsuitable for an easily installable and distributed method. This, furthermore, hinders the publication of *rirods* on the Comprehensive R Archive Network (CRAN; the official R package archive), as interoperability among operating systems is mandatory for an R package to be eligible for publication.


<!-- 
Outlining the issue / weak point / problem to be solved by this proposal. This should be a compelling section that sets the reader up for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Who it affects
 - [ ] Have there been previous attempts to resolve the problem
 - [ ] Why it should be tackled
-->
