# The proposal

<!--
This is where the proposal should be outlined. 
-->

## Overview

Recently, a REpresentational State Transfer (REST)full API has been build for iRODS. REST architectures allow connecting services at global scale [@Fielding2000], as it allows clients (users) to interact with their data via a web-based architecture with the common HTTP verbs. HTTP is an interaction protocol for the Web, where verbs like GET, PUT, POST and DELETE can interact with the resource representation through a Uniform Resource Identifier (URI). This allows for a loose coupling between the datamanagment system (iRODS) and the user, which means that the consuming application does not have to be build on the same system, or even on the same operating system. Similarly to data stored on iRODS, using the web means also that the representation of the resource does not need to conform to a stringent format, and can be any, or many, formats (e.g., text, XML, and/or JSON). This user friendliness and lose coupling allows for a radical new approach to bind iRODS to R. We therefore propose to build a new R package for iRODS; *rirods2*, to replace or supplement the former package, and, which, allows for a truly distributed computing solution by using iRODS RESTfull API.

<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->


## Detail {#sec:Detail}



<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->
