# Success
<!-- 
Projects should have a definition of done that is measurable, and a thorough understanding going in of what the risks are to delivery 
-->

## Definition of done

The deliverable "Installable package on CRAN" of Section \@ref(sec:Technical) defines achievement of the minimal viable product (Solution 1; Section \@ref(sec:Detail)). Progress on the implementation of Solutions 2 and/or 3 is seen as a bonus.
<!-- 
What does success look like? 
-->

## Measuring success

The actual success during the development phase is measured by the number of contributions and the number of research institutes, laboratories and universities that we can engage with. The success of the developed package is measured by use-cases through download statistics, and for development purposes, by tracking how many packages will integrate this package.
<!-- 
How will we know when success is achieved, what markers can we use along the way 
-->

## Future work
<!-- 
How could this be extended / developed in the future by yourself and/or the community in general?
-->
It will enable consulting and implementing better resources for data management in academic settins as well as help teaching efforts focussing on data management and reproducible science. In addition, we consider writing a paper concerning the package for the [Journal of Open Source Software](https://joss.theoj.org/), and continuously advertise usage of the package by actively engaging with target user-base at conferences and on social media. 


## Key risks

One of the key risks in the process of developing the package is the selection of the appropriate solution (as listed in Section \@ref(sec:Detail)). Hence the early identification of this bottleneck and the formulation of three contingency plans (i.e., the different solutions) will help alleviate these risks to some extend. Problems and delays in terms of coordinating community feedback (especially desired use-cases) and contributions (mainly solutions as listed above) could stem from a lack of consensus on the specific solution to be adopted. Hence we aim to address this at the earliest stages of the project (Months 1--2). 

<!-- 
What sort of things could come up that can delay or break the project?

 - [ ] People
 - [ ] Processes
 - [ ] Tooling & Technology
 - [ ] Costs

-->
