# Project plan

## Start-up phase {#sec:Start}

The development of *rirods2* is a central part of broadening the user base of iRODS and facilate for data magement tools for the UU. Thus *rirods2* is meant to be conducive to innovation within an acadamic environment, and foster inclusiveness through open science. In turn, package development encompasses soliciting specific use-cases from the R community and laboratory facilities. A close collaboration with the Department of Earth Sciences, Utrecht University (UU), the Netherlands, and their analytical laboratory infrastructure, is already foreseen. Nonetheless, the development will benefit from having a good overview of the types of data and data models produced by analytical equipment in a range of laboratories. We will opt for an [MIT license](https://opensource.org/licenses/MIT) and a code of conduct, which will follow the [Contributor Covenant](https://www.contributor-covenant.org/) guide lines. Combined this ensures that contributions to the package can be done in a safe, inclusive, welcoming, and harassment-free environment conducive for collaborative package development, and ensuring down-stream re-usage of the developed software. Reporting of the progress of the project to both (lab-)users and developers will help ensure that we stay on track and thus develop a solution that has a broad future implementation.

<!-- The licensing could possibly constrain the integration of some C++ libraries.  -->

<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->


## Technical delivery {#sec:Technical}

The duration of the project will be 12 months. The "**deliverable**" gives a convenient measure of project's progress.

***Months 1--2***

- Documentation of use-cases.
- Determine the feasibility of the solutions (\@ref(sec:Detail)) and make a selection.
- **Deliverable:** We report our finding on the current state of iRODS integration at UU.

***Months 3--4***

- Start with basic package set-up with *devtools* [@devtools], create source scripts in C++ for loading data files.
- Follow best practices from the start of package development; e.g., documenting progress, maintaining a functioning Git master branch and usage of development branches for experimental updates. This will be published on GitHub from the start, and tags are created when milestones are hit to benefit progress tracking. In addition, unit tests are constantly developed to ensure that a particular behavior of a function is, and remains, correct (and also regularly checking code coverage of said tests). Lastly, we test code, portability, and documentation with `R CMD check` and with continuous integration provided by GitHub Workflows.
- **Deliverable:** A GitHub repo with the basis of the package.

***Months 5--6***

- Minimal functionality to ..ses.
- **Deliverable:** A tag in the GitHub repo annotating the milestone of a functioning solution.

***Months 7--8***

- Include iRODS functionality.
- Present package at conference(s) targeting users (natural science conference) and/or developers (R or open science conference).
- **Deliverable:** Installable package on GitHub with documentation as vignettes and website with *pkgdown* [@pkgdown].

***Months 9--10***

- Test use cases for the integrated R and iRODS workflows (UU).
- **Deliverable:** A tag in the GitHub repo annotating the milestone of successful integration with iRODS.

***Months 11--12***

- Publish on CRAN.
- Include usage of package in teaching/course material provided at the UU.
- **Deliverable:** Installable package on CRAN.

<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

## Other aspects

We will garner attention on the problem surrounding data management on open science, and our proposed solutions to garner these problems, through several channels (see also the timeline above). We actively seek to advertise the product by presenting our finding at conferences; either user-specific (natural science conference) and/or the developers community (e.g. R or open science conference).

<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->
